name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pytest-asyncio pytest-cov ruff mypy bandit pip-audit

      - name: Ruff (lint)
        run: ruff check backend

      - name: Mypy (type check)
        run: mypy backend

      - name: Pytest
        run: pytest -q --asyncio-mode=auto --cov=backend --cov-report=term-missing

      - name: Bandit
        run: bandit -r backend -ll

      - name: pip-audit
        run: pip-audit -r backend/requirements.txt

  frontend-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        working-directory: web
        run: npm ci

      - name: Lint
        working-directory: web
        run: npm run lint

  security:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - backend-tests
      - frontend-lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"

      - name: Build backend image
        run: docker build -f backend/Dockerfile -t echo-backend:ci .

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: echo-backend:ci
          severity: CRITICAL,HIGH
          ignore-unfixed: true
